site_name: Documentação Projeto Farmax
site_description: Documentação Análise de Dados Projeto Farmax
site_author: A3DATA
site_url: https://docBIFARMAX.com/
copyright: Desenvolvido por A3DATA
nav:
- Bem - vindo(a): index.md 

- Análise de Dados: 
  - Antes de Começar: ad/Análise_de_Dados.md
  - Corporativo: ad/Corporativo.md
  - Marketing: 
    - Lançamentos: ad/Marketing_Lançamentos.md
    - Tabela de Produtos: ad/Marketing_Tab_Produtos.md
  - Qualidade:
    - Mapa de Distribuição: ad/Qualidade_Mapa_de_Distribuição.md
    - Mapa de Rastreabilidade: ad/Qualidade_Mapa_de_Rastreabilidade.md
    - Mapa de Devolução: ad/Qualidade_Mapa_de_Devolução.md
    - Mapa de Entrada: ad/Qualidade_Mapa_de_Entrada.md
    - Liberação de Pedidos: ad/Qualidade_Liberação_de_Pedidos.md
  - Operações: 
    - PMP: ad/Operações_PMP.md
    - Planejamento de Produção: ad/Operações_Planejamento_Producao.md
- Engenharia de Dados: 2_Engenharia.md

theme:
    name: material
    language: pt
    favicon: img/Selo_Fundo_Branco.ico.png
    logo: img/Logo_Frase_Branco.ico.png
    features: 
      - search.suggest
      - search.highlight
    palette:
      - scheme: default
        primary: indigo
        accent: blue
        toggle:
            icon: material/toggle-switch-off-outline
            name: Modo Escuro
      - scheme: slate
        primary: blue
        toggle:
            icon: material/toggle-switch
            name: Modo Claro
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2 # Nível básico dos cabeçalhos
        separator: "_"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - attr_list
    