site_name: Documentação Projeto Farmax
site_description: Documentação Análise de Dados Projeto Farmax
site_author: A3DATA
site_url: https://docBIFARMAX.com/
copyright: Desenvolvido por A3DATA
nav:
- Bem - vindo(a): index.md 

- Análise de Dados: 
  - Antes de Começar: 1_Análise de Dados.md
  - Corporativo: 1.1_Corporativo.md
  - Marketing: 
    - Lançamentos: 1.2_Lançamentos.md
    - Tabela de Produtos: 1.3_Tab. Produtos.md
  - Qualidade:
    - Mapa de Distribuição: 1.4_Mapa de Distribuição.md
    - Mapa de Rastreabilidade: 1.5_Mapa de Rastreabilidade.md
    - Mapa de Devolução: 1.6_Mapa de Devolução.md
    - Mapa de Entrada: 1.7_Mapa de Entrada.md
    - Liberação de Pedidos: 1.8_Liberação de Pedidos.md
  - Financeiro: 1.9_Financeiro.md
  - Logística: 1.10_Logística.md
  - Operações: 1.11_Operações.md
- Engenharia de Dados: 2_Engenharia de Dados.md

theme:
    name: material
    language: pt
    favicon: img/Selo_Fundo_Branco.ico.png
    logo: img/Logo_Frase_Branco.ico.png
    features: 
      - search.suggest
      - search.highlight
    palette:
      - scheme: default
        primary: indigo
        accent: blue
        toggle:
            icon: material/toggle-switch-off-outline
            name: Modo Escuro
      - scheme: slate
        primary: blue
        toggle:
            icon: material/toggle-switch
            name: Modo Claro
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 2 # Nível básico dos cabeçalhos
        separator: "_"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - attr_list
    